spring:
  application:
    name: ryokouikitai
  profiles:
    active : secret
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: none
      show_sql: true
      format_sql: true
      use_sql_comments: true
  redis:
    host: localhost
    port: 6379

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
